// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FetchRoom struct {
	ID string `json:"id" bson:"_id"`
}

type FetchUser struct {
	ID string `json:"id" bson:"_id"`
}

type NewRoom struct {
	HostName string `json:"host_name"`
	Token    string `json:"token"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Room struct {
	ID      string  `json:"_id" bson:"_id"`
	Host    *User   `json:"host"`
	Token   string  `json:"token"`
	Players []*User `json:"players"`
}

type User struct {
	ID     string `json:"_id" bson:"_id"`
	Name   string `json:"name"`
	Answer string `json:"answer"`
	Score  int    `json:"score"`
}
